### ISSUE TITLE
Incompatibility with Essential Mod

### ISSUE THREAD

**Issue by migueacastro** [Wilyicaro/Legacy-Minecraft#260]
Game interface gets like this while using Essential mod. I really love this mod and I want to use this online mode.
![Screenshot_20240507_234927](https://github.com/Wilyicaro/Legacy-Minecraft/assets/54249734/12cc40cb-5bab-43da-bfd5-46a2d73e07ca)

**Comment by bblyse001** [comment]
If you exit Fullscreen and go Fullscreen again it fixes the current screen gui/ui. (Double F11)

**Comment by migueacastro** [comment]
It fixes the current gui until I open/close, another menu, so it is still unplayable.

**Comment by Daralexen05** [comment]
That is a shame. I guess that I will have to wait until this is fixed and a 1.20.1 port is made.

**Comment by Wilyicaro** [comment]
Fixed in 1.6.3

**Comment by migueacastro** [comment]
It got a bit better, but this is still happening to me on the latest version of both mods (Before/after pressing F11) 
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/54249734/e3ed1b89-0b4a-4c4e-9dfd-517d459c4b2c)  
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/54249734/b2029c07-d385-4125-9234-447dac845650)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/54249734/1e9b752b-f94c-4d6a-ad95-b2b204120d95)
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/54249734/881d81a3-4ee5-4867-b891-d00357459258)

**Comment by Wilyicaro** [comment]
Fixed the really huge interface, I can't stop specifically Essential mod from messing up the screen scale
