### ISSUE TITLE
Character doesn't move if you hold the joystick in a direction on a menu and then close the menu

### ISSUE THREAD

**Issue by G01dY05h1** [Wilyicaro/Legacy-Minecraft#275]
Character doesn't move if you hold the joystick in a direction on a menu and then close the menu.

Example: Moving in the inventory while moving the joystick, continue holding the joystick and close the inventory, you can't move until you let go of the joystick and then move it again

**Comment by G01dY05h1** [comment]
(this was fixed before, but is back again)

**Comment by G01dY05h1** [comment]
Does not affect right stick

**Comment by Wilyicaro** [comment]
Fixed in 1.6.3a, thanks for reporting.

**Comment by G01dY05h1** [comment]
Unfortunately, my tests have concluded that (at least on my DualSense) this bug is still in the mod

**Comment by Wilyicaro** [comment]
I am 100% sure that this has been fixed

**Comment by G01dY05h1** [comment]
Well, I can see in the commit that (from my small understanding of code) a fix was made, or at least attempted, but in my actual testing, the bug is still there

**Comment by Wilyicaro** [comment]
Did you actually update the mod? Show evidence that this continues to happen

**Comment by G01dY05h1** [comment]
I did update the mod, and I just downgraded, I'll update again to see if it's still there
